;;; calisthenics-exercises.el --- Hybrid Calisthenics exercises data -*- lexical-binding: t; -*-
(defvar wilf/calisthenics-exercises-alist
  '(("Pushups"
     . ("Wall Pushups"
        "Incline Pushups"
        "Advanced Incline Pushups"
        "Knee Pushups"
        "Full Pushups"
        "Narrow Pushups"
        "Side-Staggered Pushups"
        "Archer Pushups"
        "Sliding One-Arm Pushups"
        "One-Arm Pushups"
        "Advanced One-Arm Pushups"))
    ("Pullups"
     . ("Wall Pullups"
        "Horizontal Pullups"
        "Advanced Horizontal Pullups"
        "Jackknife Pullups"
        "Full Pullups"
        "Narrow Pullups"
        "One Hand Pullups"
        "Advanced One Hand Pullups"
        "Archer Pullups"
        "One Arm Pullups"))
    ("Squats"
     . ("Jackknife Squats"
        "Assisted Squats"
        "Half Squats"
        "Full Squats"
        "Narrow Squats"
        "Side Staggered Squats"
        "Front Staggered Squats"
        "Assisted One Leg Squats"
        "One Leg Chair Squats"
        "One Leg Squats"))
    ("Leg Raises"
     . ("Knee Raises"
        "Advanced Knee Raises"
        "Alternating Leg Raises"
        "Full Leg Raises"
        "Tuck Plow Raises"
        "Plow Raises"
        "Hanging Knee Raises"
        "Advanced Hanging Knee Raises"
        "Hanging Leg Raises"
        "Toe to Bars"))
    ("Bridges"
     . ("Glute Bridges"
        "Straight Bridges"
        "Wall Bridges"
        "Incline Bridges"
        "Head Bridges"
        "Full Bridges"
        "Wheel Bridges"
        "Tap Bridges"
        "Wall Walking Bridges"
        "Stand to Stand Bridges"))
    ("Twists"
     . ("Straight Leg Twists"
        "Bent Leg Twists"
        "Full Twists"))
    ("Dips"
     . ("Bench Dips"
        "Bar Dips"
        "Straight Bar Dips"
        "Korean Dips"
        "Ring Dips"
        "Assisted Dips"
        "Full Dips"
        "Weighted Dips"))
    ("Grips"
     . ("Towel Hangs"
        "Dead Hangs"
        "Farmer Carries"
        "Plate Pinches"
        "Finger Extensions"
        "Captains of Crush"
        "Towel Pullups"
        "Thick Bar Holds")))
  "Alist of categories → list of Hybrid Calisthenics exercises.")


(provide 'calisthenics-exercises)
;;; calisthenics-exercises.el ends here
