general.import = [
    "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[font]
size = 11.0

[font.normal]
family = "Iosevka Comfy Fixed"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
