general.import = [
    "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[font]
size = 8.0

[font.normal]
family = "Iosevka Comfy Motion"
style = "semilight"

[window]
opacity = 1

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true