import = [
    "~/.config/alacritty/themes/themes/argonaut.toml"
]

[font]
size = 11.0

[font.normal]
family = "Iosevka Comfy Motion"
style = "semilight"

[window]
opacity = 0.8

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true